const stockProductos = [
    {   
        id: 1,
        nombre: "Goku" ,
        precio: 20000 ,
        desc: "Producto a la venta" ,
        img: "./media/Goku1.png",
    },
    {
        id: 2,
        nombre: "Vegeta" ,
        precio: 20000,
        desc: "Producto a la venta",
        img: "./media/Vegeta1.png",
    }, 
    {
        id: 3,
        nombre: "Trunks" ,
        precio: 20000 ,
        desc: "Producto a la venta",
        img: "./media/Trunks1.png",
    }, 
    {
        id: 4,
        nombre: "Broly",
        precio: 25000,
        desc: "Producto a la venta",
        img: "./media/Broly1.png",
    }, 
    {
        id: 5,
        nombre: "Freezer",
        precio: 20000,
        desc: "Producto a la venta",
        img: "./media/Freeza0.png",
    }, 
    {
        id: 6,
        nombre: "Bardock",
        precio: 20000,
        desc: "Producto a la venta",
        img: "./media/Bardock1.png",
    }, 
    {
        id: 7,
        nombre: "Gogeta",
        precio: 25000,
        desc: "Producto a la venta",
        img: "./media/Gogeta3.png",
    }, 
    {
        id: 8,
        nombre: "Freezer bust",
        precio: 15000,
        desc: "Producto a la venta",
        img: "./media/Bust1.png",
    }, 
    {
        id: 9,
        nombre: "Goku bust",
        precio: 15000,
        desc: "Producto a la venta",
        img: "./media/GokuBust1.png",
    }, 
    {
        id: 10,
        nombre: "Piccolo",
        precio: 20000 ,
        desc: "Producto a la venta",
        img: "./media/Piccolo3.png",
    }, 
    {
        id: 11,
        nombre: "Vegeta bust" ,
        precio: 15000,
        desc: "Producto a la venta",
        img: "./media/VegetaBust1.png",
    }, 
    {
        id: 12,
        nombre:"Vegetto" ,
        precio: 25000,
        desc: "Producto a la venta",
        img: "./media/Vegetto2.png",
    }, 
    
    {
        id: 13,
        nombre: "Bardock bust" ,
        precio: 15000,
        desc: "Producto a la venta",
        img: "./media/Bardock2.png",
    }, 
    {
        id: 14,
        nombre: "Goku final",
        precio: 25000 ,
        desc: "Producto a la venta",
        img: "./media/Goku3.png",
    }, 
    {
        id: 15,
        nombre: "Trunks bust",
        precio: 15000,
        desc: "Producto a la venta",
        img: "./media/Trunks1.png",
    },
    {
        id: 16,
        nombre: "Vegeta ultra ego",
        precio: 25000,
        desc: "Producto a la venta",
        img: "./media/UltraEgo3.png",
    }, 
    {
        id: 17,
        nombre: "Cell" ,
        precio: 20000,
        desc: "Producto a la venta",
        img: "./media/Cell4.png",
    }, 
    
]